name: Dotnet MSDeploy WebApp

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: windows-latest
    env:
      APP_NAME: 'webapi'
      PHYSICAL_PATH: 'C:\deployments\webapi'
      IIS_WEBSITE_NAME: 'Default Web Site'
      IIS_SERVER_COMPUTER_NAME: '139.180.144.223'
      IIS_SERVER_USERNAME: 'Administrator'
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: Stop Application Pool
      shell: cmd
      run: |
        "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -allowUntrusted:true -source:recycleApp -dest:recycleApp="${{ env.IIS_WEBSITE_NAME }}/${{ env.app-name }}",recycleMode="StopAppPool",wmsvc="${{ env.IIS_SERVER_COMPUTER_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",AuthType="Basic"

    - name: Deploy Application
      shell: cmd
      run: |
        "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -allowUntrusted:true -source:iisApp="${{ env.physical-path }}" -dest:iisApp="${{ env.IIS_WEBSITE_NAME }}/${{ env.app-name }}",wmsvc="${{ env.IIS_SERVER_COMPUTER_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",AuthType="Basic" -setParamFile="${{ env.physical-path }}\SetParameters.xml"

    - name: Start Application Pool
      shell: cmd
      run: |
        "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -allowUntrusted:true -source:recycleApp -dest:recycleApp="${{ env.IIS_WEBSITE_NAME }}/${{ env.app-name }}",recycleMode="StartAppPool",wmsvc="${{ env.IIS_SERVER_COMPUTER_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}",AuthType="Basic"
